package com.example.safehome.constants

class AppConstants {

    object RetrofitApis {
        //  const val BASE_URL = "https://dummy.restapiexample.com/"
        //  const val BASE_URL = "https://jsonplaceholder.typicode.com/"

        // safe home apis
        const val BASE_URL = "https://api.msafehome.com/api/"
        const val BASE_QA_URL = "https://qa.msafehome.com/api/"

        const val mobileSignUp = "register/MobileSignUp"
        const val resendSingUpOTP = "login/ResendSingupOTP"
        const val verifySignUpOTP = "login/VerifySignupOTP"
        const val mobileLogin = "login/MobileLogin"
        const val communityStates = "login/GetCommunityStates"
        const val communityCities = "login/GetCommunityCities"
        const val allCommunities = "login/GetAllCommunities"
        const val getBlocks = "login/GetBlocks"
        const val getFlats = "login/GetFlats?"
        const val updateUserDetails = "login/UpdateUserDetails"
        const val verifyLoginOTP = "login/VerifyLoginOTP"
        const val getLoginUserDetails = "users/GetLoginUserDetails?"
        const val resendLoginOTP = "login/ResendLoginOTP"
        const val getFamilyMemberDetails = "users/GetFamilyMemberdetailsbyResidentId?"
        const val addMyFamily = "users/AddMyFamily"
        const val updateMyFamily = "users/UpdateMyFamily"
        const val deleteFamilyMember = "users/DeleteFamilyMember"
        const val addMyVehicle = "users/AddMyVehicle"
        const val getAllVehiclesbyUserId = "users/GetAllVehiclesbyResidentId"
        const val updateMyVehicle = "users/UpdateMyVehicle"
        const val deleteVehicle = "users/DeleteVehicle"
        const val getAllTenants = "users/GetAllTenants"
        const val addTenant = "users/AddTenant"
        const val updateTenant = "users/UpdateTenant"
        const val deleteTenant = "users/DeleteTenant"
        const val getAllVehicleModels = "users/GetAllVehicleModels"
        const val getFlatByFlatId= "users/GEtFlatByFlatId?"
        const val getDueMaintenanceDetailsByResident = "maintenance/GetDueMaintenanaceDetailsByResident?"
        const val UpdateMaintenancePayment = "maintenance/UpdateMaintenancePayment"

        const val getAllMaintenanceCategorys= "maintenance/GetAllMaintenanceCategorys"
        const val getPaidMaintenanaceDetailsByResident= "maintenance/GetPaidMaintenanaceDetailsByResident"
        const val getAllUpcomingEvents= "event/GetAllUpcomingEvents"
        const val getAllcompletedEvents= "event/GetAllcompletedEvents"
        const val getAllFacilities= "facility/GetAllFacilities"
        const val getAllBookedFacilities= "facility/GetAllBookeFacilities"
        const val bookFacility= "facility/BookFacility"
        const val updateBookFacility = "facility/UpdateBookFacility"
        const val deleteFacility= "facility/DeleteBookFacility"
        const val updatePaymentForBookFacility = "facility/UpdatePaymentForBookFacility"
        const val GetServiceTypeswithServiceCount = "services/GetServiceTypeswithServiceCount"
        const val GetServiceDataByServiceType = "services/GetServiceDataByServiceType"
        const val getServiceProvidedByServiceType= "masters/GetServiceProvidedByServiceType"
        const val addServiceBooking = "services/AddServiceBooking"
        const val updateServiceBooking= "services/UpdateServiceBooking"
        const val deleteServiceBookingById= "services/DeleteServiceBookingById?"
        const val getAllBookedServiceByResidentId= "services/GetAllBookedServiceByResidentId?"
        const val getStaffPaymentHistory = "services/GetStaffPaymentHistory"
        const val getAllServiceTypes= "services/GetAllServiceTypes"
        const val updateServiceBookingPayment= "services/UpdateServiceBookingPayment"
        const val getDailyHelpStaff = "services/GetStaffTypeswithStaffCount"
        const val getDailyHelp = "services/GetStaffDataByStaffType"
        const val getDailyHelpBookingList = "services/GetAllBookedStaffByResidentId"
        const val addStaffBooking= "services/AddStaffBooking"
        const val updateStaffBooking = "services/UpdateStaffBooking"
        const val deleteBookStaff= "services/DeleteBookStaff?"
        const val updateStaffBookingPayment = "services/UpdateStaffBookingPayment"

        const val dailyHelpHistory= "services/GetStaffPaymentHistory"
        const val yearList= "masters/GetYearsforDropDown"
        const val staffList= "masters/GetAllStaffTypes"
        const val getallNoticesStatus= "notice/GetallNoticesStatus?"
        const val updateNoticeRead= "notice/UpdateNoticeRead?"
        const val getPersonalComplaints= "notice/GetallNoticesStatus"

        const val getAllUpcomingMeetings= "meeting/GetAllUpcomingMeetings"
        const val getAllCompletedMeetings= "meeting/GetAllCompletedMeetings"
        const val getAllResponseStatusMaster = "meeting/GetAllResponseStatusMaster"
        const val updateAttendingResponseStatus = "meeting/UpdateAttendingResponseStatus"

        const val getAllPollDetails= "notice/GetAllUserPollDetails"
        const val getPollResults= "notice/GetPollResults"
        const val addPoll= "notice/AddPollDetails"
        const val updatePoll= "notice/UpdatePollDetails"
        const val getKeepForDropDown= "masters/GetKeepForDropDown"
        const val getAllPostedToDropDown = "masters/GetAllPostedToDropDown"
        const val deletePollDetails= "notice/DeletePollDetails?"


        const val getAllForumDetails= "notice/GetAllUserForumDetails"
        const val addForum= "notice/AddForumDetails"
        const val updateForum= "notice/UpdateForumDetails"
        const val deleteForumDetails= "notice/DeleteForumDetailsById?"
        const val getAllCommentDetailsByForumId= "notice/GetAllCommentDetailsByForumId?"
        const val addForumCommentDetails = "notice/AddForumCommentDetails"
        const val addForumCommentReply = "notice/AddForumCommentReply"
        const val deleteForumCommentDetails = "notice/DeleteForumCommentDetails?"

        const val getAllVisitorDetails= "visitors/GetAllVisitorDetails"
        const val getAllVisitorTypeDropdown= "masters/GetAllVisitorTypeDropdown"
        const val getServiceProviderDropdown= "masters/GetAllVisitorTypeServiceProviderDropdown"
        const val GetVisitorScheduleDropdown= "masters/GetVisitorScheduleDropdown"
        const val postVisitorAPI= "visitors/Invitevisitor"
        const val updateVisitorAPI= "visitors/UpdateVisitorDetails"
        const val getAllApprovalStatusTypes= "users/GetAllApprovalStatusTypes?StatusFor=visitor"
        const val deleteVisitorDetails= "visitors/DeleteVisitorDetails?VisitorId=1"
        const val getStaffdetailsbyStafftypeIdDropdown = "masters/GetStaffdetailsbyStafftypeIdDropdown"
        const val getpoliciesAPI= "complaint/GetAllCommintyPoliciesDetails"
        const val getEmergentContactAPI= "others/GetAllEmergencyContactDetails"
        const val getEmergentContactCategoryAPI= "masters/GetAllEmergencyContactTypeDetailsDropDown"
        const val updatePollVotingStatus= "notice/UpdatePollVotingStatus"
        const val getAllUserENewsDetails= "others/GetAllUserENewsDetails"
        const val getAllAssociatonMembers= "users/GetAllAssociatonMembers"
        const val getAllRelationShipTypes= "users/GetAllRelationShipTypes"
        const val getAlertUrl= "others/GetAllAlertDetails"
        const val deleteAlertUrl= "others/DeleteAlertDetails"
        const val GetAllEmergencyTypeDetailsDropDown= "masters/GetAllEmergencyTypeDetailsDropDown"
        const val SendAlertDetails= "others/SendAlertDetails"
        const val UpdateAlertDetails= "others/UpdateAlertDetails"
    }
}